server:
  port: ${PORT:0}

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: familiasdb
      host: localhost
      port: 27019
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
logging:
  level:
    sql: debug
